development:
  secret_key_base:  pk_live_aE6QW1m64Wz6UttBUpnhCk21 
  some_api_key: sk_live_QXdG1kdkOBii7VE68nHA67MH
  stripe_publishable_key:  pk_test_KVobsqBe7wm6KAYOONf4lKfj
  stripe_secret_key: sk_test_IizjmEfPcQ4RzWiag1aXB337
  
production:
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']